---
title: "Analysis and Business Questions"
output: html_document
date: "2023-10-20"
---

## Analysis Questions

-   Which brands generates the most revenue?

-   Which brands have the most refunds ?

-   Is there a difference on rate of refunds on a product based on vendors ?

-   Which state generates the most revenue? And which state for revenue per customer?

-   Does each region / state have different preferences on product?

-   Which region / state needs more store?

-   What is the effect of color/style/size on a product's sale?

-   Which products are more profitable ? (SPrice -- Cost) / Cost

-   Which states have the highest quantities in their orders ?

-   Which department generates more profit / needs more discount ?

-   Number of registers in a store

-   How many transactions per registers in a store

-   Do some stores perform better than others? Why?

-   How many different styles does a product have ?

## Business Questions



### Identifying Transactions with High Chance of a Refund 

**Classifying the transactions with high chance of return**

The reason of a refund for a product can depend on many reasons such as a defected product supplied by the vendor, the time/season of the purchase, change in the price point after the sale, products that it was bought together with
external economic factors or any other product specification.

This would allow the firm to have a better understanding of the returns with a help of an explainable model and the inventory management can be managed according to this.


### Identifying the stores in need

**Finding the need of help in a store, to suggest providing more help to the store or opening a new one close by.**

Creating a new feature that shows how busy a store is based on things like; How many registers are there in a store, How many transactions and transactionsPerRegisters (new feature), the population in the area and percent of population that visits the store and then classifying a store as "requires need"

### Providing guidance for customers before purchase

**Answering questions regarding product specifications by an LLM**

Fine-tuning an LLM with information regarding products and deploying as an chat-bot agent to aid customers that seek help before a purchase to increase the chance of sales.
