---
title: "R Notebook"
output: html_notebook
---


```{r}

# This can be done through R studio as well.

library(usethis) 
usethis::edit_r_environ()

# when the tab opens up in R studio, add this to the 1st line: R_MAX_VSIZE=100Gb (or whatever memory you wish to allocate).
```


```{r setup, include=FALSE}

# Set working directory

knitr::opts_chunk$set(echo = TRUE)
knitr::opts_knit$set(root.dir = "~/Desktop/Northwestern/Classes/Fall 23/Everything Starts with Data/Project/Dillards")
getwd()


```


```{r}

library(lubridate) # time operations

library(reshape2) # reshaping data (melt, dcast, recast)

library(dplyr)

library(data.table)

library(ggplot2)


```


```{r}


deptinfo = read.table('deptinfo.csv', sep = ',', header = FALSE, 
                       strip.white = TRUE, quote = "", na.strings = "NA", 
                       stringsAsFactors = T, fill = TRUE,
                       col.names = c('dept', 'deptDesc', 'unknown'))


deptinfo


```


```{r}



strinfo = read.table("strinfo.csv", sep = ",", header = FALSE, 
                      strip.white = TRUE, quote = "", na.strings = "NA", 
                      stringsAsFactors = T, fill = TRUE,
                      col.names = c("store", "city", "state", "zip", "unknown"))
strinfo


```




```{r}




skuinfo = read.table('skuinfo.csv', sep = ',', header = FALSE, 
                       strip.white = TRUE, quote = "", na.strings = "NA", 
                       stringsAsFactors = T, fill = TRUE,
                       col.names = c('sku', 'dept', 'classId', 'upc', 'style', 'color', 'size',
                                     'packSize', 'vendor', 'brand', 'unknown1', 'unknown2'))

skuinfo


```


```{r}


skstinfo = read.table('skstinfo.csv', sep = ',', header = FALSE, 
                       strip.white = TRUE, quote = "", na.strings = "NA", 
                       stringsAsFactors = T, fill = TRUE,
                       col.names = c('store', 'sku', 'cost', 'retail', 'unknown'))


skstinfo

```






```{r}


trnsact = read.table('trnsact.csv', sep = ',', header = FALSE, 
                      strip.white = TRUE, quote = "", na.strings = "NA", 
                      stringsAsFactors = T, fill = TRUE,
                      col.names = c('sku', 'store', 'register', 'trannum', 'seq', 
                                    'saleDate', 'stype', 'quantity', 'orgPrice',
                                    'sPrice', 'amt', 'interId', 'mic', 'unknown'))


trnsact



```


```{asis}

Less memory will be used if colClasses is specified as one of the six atomic vector classes. This can be particularly so when reading a column that takes many distinct numeric values, as storing each distinct value as a character string can take up to 14 times as much memory as storing it as an integer.

Using nrows, even as a mild over-estimate, will help memory usage.

Using comment.char = "" will be appreciably faster than the read.table default.


```



```{r}

str(strinfo)

summary(strinfo)

```

```{r}

strinfo %>%
  group_by(state) %>%
  summarize(count_city = length(city)) %>%
  arrange(desc(count_city))

```



```{asis}

TX and FL has the most stores
-- adding external data to categorize them into 5 regions of the US?


```




```{r}

str(trnsact)


```


```{r}

summary(trnsact)

```




```{asis}


stype -> R: Return , P: Purchase
-- take into account when making calculations
  -- subset(trnsact, subset = (stype=="P")) 
  -- trnsact[trnsact$stype=="P", ] 



```




```{r}


trnsact %>% 
  summarise(across(everything(), ~ sum(is.na(.x))))


```





```{r}

library(naniar)
library(finalfit)

trnsact %>%
  missing_plot()


```



```{r}

# scatter plots

```



